/*
 * davyjones.h
 *
 *  Created on: Feb 7, 2019
 *      Author: Administrator
 */

#ifndef SONGS_DAVYJONES_H_
#define SONGS_DAVYJONES_H_
#include "notes.h"

const Note jonesTreb[] = {

                          {F4,2},
                          {D4,14},
                          {E5,FO},//
                          {D5,2},
                          {F5,14},
                          {G5,FO},//
                          {F5,2},
                          {A5,14},
                          {C6,EI},
                          {Bb5,EI},//
                          {F5,2},
                          {A5,14},
                          {REST,FO},//
                          {F5,2},
                          {A5,14},
                          {Bb5,FO},//
                          {G5,2},
                          {C6,14},
                          {D6,EI},
                          {Bb5,EI},//
                          {F5,2},
                          {A5,14},
                          {G5,FO},//
                          {F5,2},
                          {A5,22},//
                          {G5,2},
                          {Bb5,14},
                          {C6,FO},

                          {F5,2},//10
                          {A5,14},
                          {F5,FO},//
                          {E5,2},
                          {G5,14},
                          {Bb5,EI},
                          {A5,EI},//
                          {D5,2},
                          {F5,14},
                          {D5,FO},//
                          {C5,2},
                          {E5,14},
                          {C5,FO},//
                          {A4,HA},
                          {E5,FO},//
                          {F4,2},
                          {D5,14},
                          {REST,FO},//
                          {F4,2},
                          {D5,14},
                          {REST,FO},//
                          {REST,48},//

                          {F4,2},//19
                          {D5,14},
                          {E5,FO},//
                          {D5,2},
                          {F5,14},
                          {G5,FO},//
                          {F5,2},
                          {A5,14},
                          {C6,EI},
                          {Bb5,EI},//
                          {F5,1},
                          {A5,15},
                          {REST,FO},//
                          {F5,1},
                          {A5,15},
                          {REST,FO},//
                          {F5,1},
                          {A5,15},
                          {Bb5,FO},//
                          {G5,1},
                          {C6,15},
                          {D6,EI},
                          {Bb5,EI},//

                          {F5,1},//25
                          {A5,15},
                          {G5,FO},//
                          {F5,1},
                          {A5,23},//
                          {G5,1},
                          {Bb5,15},
                          {C6,FO},//
                          {F5,1},
                          {A5,15},
                          {F5,FO},//
                          {E5,1},
                          {G5,15},
                          {Bb5,EI},
                          {A5,EI},//
                          {D5,1},
                          {F5,15},
                          {D5,FO},//

                          {C5,1},//31
                          {E5,15},
                          {C5,FO},//
                          {A4,HA},
                          {E5,FO},//
                          {D4,1},
                          {F5,15},
                          {REST,FO},//
                          {D4,1},
                          {F5,15},
                          {REST,FO},//
                          {G4,EI},
                          {A4,EI},
                          {Bb4,EI},
                          {A4,EI},
                          {Bb4,EI},
                          {Cs5,EI},//

                          {D5,TS},//36
                          {C5,TS},
                          {Bb4,TS},
                          {A4,TS},
                          {D5,TS},
                          {C5,TS},
                          {Bb4,TS},
                          {A4,TS},//
                          {E5,TS},
                          {C5,TS},
                          {A4,TS},
                          {D5,TS},
                          {F5,TS},
                          {D5,TS},
                          {A4,TS},
                          {D5,TS},//
                          {F5,TS},
                          {D5,TS},
                          {A4,TS},
                          {D5,TS},
                          {G5,TS},
                          {E5,TS},
                          {D5,TS},
                          {C5,TS},////
                          {A5,TS},
                          {F5,TS},
                          {D5,TS},
                          {F5,TS},
                          {A5,TS},
                          {F5,TS},
                          {D5,TS},
                          {F5,TS},//
                          {C6,TS},
                          {E5,TS},
                          {Bb5,TS},
                          {E5,TS},
                          {A5,TS},
                          {F5,TS},
                          {D5,TS},
                          {F5,TS},//
                          {D5,TS},
                          {A4,TS},
                          {F4,TS},
                          {A4,TS},
                          {D5,TS},
                          {A4,TS},
                          {F4,TS},
                          {A4,TS},//

                          {A5,TS},//38
                          {F5,TS},
                          {D5,TS},
                          {F5,TS},
                          {A5,TS},
                          {F5,TS},
                          {D5,TS},
                          {F5,TS},//
                          {Bb5,TS},
                          {G5,TS},
                          {D5,TS},
                          {G5,TS},
                          {C6,TS},
                          {A5,TS},
                          {E5,TS},
                          {A5,TS},//
                          {E5,TS},
                          {C5,TS},
                          {E5,TS},
                          {G5,TS},
                          {D6,TS},
                          {G5,TS},
                          {Bb5,TS},
                          {G5,TS},////
                          {A5,TS},
                          {D5,TS},
                          {A4,TS},
                          {D5,TS},
                          {A5,TS},
                          {D5,TS},
                          {A4,TS},
                          {D5,TS},//
                          {G5,TS},
                          {E5,TS},
                          {C5,TS},
                          {E5,TS},
                          {A5,TS},
                          {F5,TS},
                          {D5,TS},
                          {F5,TS},//
                          {D5,TS},
                          {A4,TS},
                          {D5,TS},
                          {A4,TS},
                          {F4,TS},
                          {A4,TS},
                          {D5,TS},
                          {F5,TS},////

                          {Bb5,TS},//40
                          {G5,TS},
                          {D5,TS},
                          {G5,TS},
                          {Bb5,TS},
                          {G5,TS},
                          {E5,TS},
                          {G5,TS},//
                          {C6,TS},
                          {G5,TS},
                          {C5,TS},
                          {G5,TS},
                          {A5,TS},
                          {F5,TS},
                          {D5,TS},
                          {F5,TS},//
                          {D5,TS},
                          {A4,TS},
                          {D5,TS},
                          {E5,TS},
                          {F5,TS},
                          {D5,TS},
                          {A4,TS},
                          {D5,TS},////
                          {G5,TS},
                          {E5,TS},
                          {Cs5,TS},
                          {E5,TS},
                          {G5,TS},
                          {E5,TS},
                          {Bb4,TS},
                          {E5,TS},//
                          {Bb5,TS},
                          {E5,TS},
                          {A5,TS},
                          {E5,TS},
                          {F5,TS},
                          {E5,TS},
                          {D5,TS},
                          {C5,TS},//
                          {D5,TS},
                          {C5,TS},
                          {Bb4,TS},
                          {A4,TS},
                          {D5,TS},
                          {A4,TS},
                          {G4,TS},
                          {A4,TS},////

                          {E5,TS},//42
                          {C5,TS},
                          {G4,TS},
                          {C5,TS},
                          {E5,TS},
                          {C5,TS},
                          {E4,TS},
                          {G4,TS},//
                          {C5,TS},
                          {G4,TS},
                          {E4,TS},
                          {G4,TS},
                          {A4,TS},
                          {E4,TS},
                          {C4,TS},
                          {E4,TS},//
                          {C4,TS},
                          {E4,TS},
                          {A4,TS},
                          {C5,TS},
                          {E5,TS},
                          {C5,TS},
                          {A4,TS},
                          {E4,TS},////
                          {A4,TS},
                          {D4,TS},
                          {A4,TS},
                          {D5,TS},
                          {D5,TS},
                          {A5,TS},
                          {D6,TS},
                          {A5,TS},//
                          {D5,TS},
                          {A4,TS},
                          {D4,TS},
                          {A4,TS},
                          {D4,TS},
                          {A3,TS},
                          {D4,TS},
                          {A3,TS},//
                          {D4,TS},
                          {Ds4,TS},
                          {E4,TS},
                          {F4,TS},
                          {Fs4,TS},
                          {G4,TS},
                          {Gs4,TS},
                          {A4,TS},//

                          {B3,TS},//44
                          {D4,TS},
                          {Fs4,TS},
                          {B4,TS},
                          {D5,TS},
                          {Fs5,TS},
                          {B6,TS},
                          {D6,TS},//
                          {F6,TS},
                          {E6,TS},
                          {D6,TS},
                          {C6,TS},
                          {B5,TS},
                          {A5,TS},
                          {G5,TS},
                          {Fs5,TS},
                          {F5,TS},
                          {E5,TS},
                          {Ds5,TS},
                          {D5,TS},
                          {Cs5,TS},
                          {C5,TS},
                          {B4,TS},
                          {Bb4,TS},////
                          {Ab4,EI},
                          {Ab5,EI},
                          {Bb5,EI},
                          {Cb5,3},
                          {REST,1},
                          {Cb5,EI},
                          {Db6,EI},//

                          {Eb6,EI},
                          {Fb6,EI},
                          {Gb6,SI},
                          {Fb6,SI},
                          {Eb5,SI},
                          {Cb4,SI},
                          {Eb4,SI},
                          {Db5,SI},
                          {Ab5,EI},//
                          {Eb6,3},
                          {REST,1},
                          {Eb6,EI},
                          {Fb6,EI},
                          {Gb6,3},
                          {REST,1},
                          {Gb6,EI},
                          {Ab6,SI},
                          {Fb6,SI},//
                          {Eb6,3},
                          {REST,1},
                          {Eb6,EI},
                          {Db6,EI},
                          {Eb5,SI},
                          {Ab4,SI},
                          {Eb4,SI},
                          {Db5,SI},
                          {Bb4,SI},
                          {Cb4,SI},

                          {Fb6,EI},
                          {Cb5,EI},
                          {Gb6,EI},
                          {Eb6,FO},
                          {Cb5,EI},//
                          {Db6,3},
                          {REST,1},
                          {Db6,EI},
                          {Fb6,SI},
                          {Eb6,SI},
                          {Cb5,FO},
                          {Ab5,EI},////
                          {Bb4,TS},
                          {REST,TS},
                          {Gb4,SI},
                          {Eb4,SI},
                          {Gb4,TS},
                          {REST,TS},//
                          {Gb4,SI},
                          {Eb4,TS},
                          {REST,TS},
                          {Eb4,SI},
                          {Gb4,SI},//
                          {Bb4,SI},
                          {Eb4,SI},
                          {Bb4,SI},
                          {Eb5,SI},////

                          {Ab4,SI},
                          {Bb4,SI},
                          {Ab4,SI},
                          {Cb4,SI},//
                          {Eb5,SI},
                          {Ab5,SI},
                          {Bb5,SI},
                          {Eb5,SI},//
                          {Ab5,SI},
                          {Cb5,SI},
                          {Ab5,SI},
                          {Eb6,SI},////
                          {Ab6,24},////

                          {B5,HA},//54
                          {Cs6,FO},//
                          {D6,HA},
                          {E6,FO},//
                          {Fs5,HA},
                          {A5,EI},
                          {G5,EI},//
                          {D6,2},
                          {Fs6,14},
                          {REST,FO},//
                          {D6,2},
                          {Fs6,14},
                          {REST,1},
                          {G6,7},//
                          {REST,1},
                          {E6,2},
                          {A6,13},
                          {B6,EI},
                          {G6,EI},//

                          {Fs6,HA},
                          {E6,FO},//
                          {Fs6,HA},
                          {REST,FO},//
                          {E6,2},
                          {G6,14},
                          {A6,FO},//
                          {Fs6,HA},
                          {D6,FO},//
                          {G5,2},
                          {E6,14},
                          {G6,EI},
                          {Fs6,EI},//
                          {D6,HA},
                          {B5,FO},//

                          {Cs6,HA},
                          {A5,FO},//
                          {Fs5,HA},
                          {Cs6,FO},//
                          {B5,HA},
                          {REST,FO},
                          {B5,32}

};

const Note jonesBass[] = {

                          {D5,FO},
                          {A5,FO},
                          {REST,FO},//
                          {D5,FO},
                          {A5,FO},
                          {E5,FO},
                          {D5,FO},
                          {A5,FO},
                          {A5,EI},
                          {G5,EI},//
                          {D5,FO},
                          {A5,FO},
                          {REST,FO},//
                          {D5,FO},
                          {A5,FO},
                          {G5,FO},//
                          {D5,FO},
                          {G6,FO},
                          {REST,FO},//
                          {D5,FO},
                          {A5,FO},
                          {REST,FO},//
                          {D5,FO},
                          {A5,FO},
                          {REST,FO},//
                          {G5,FO},
                          {D6,FO},
                          {REST,FO},//

                          {D5,FO},//10
                          {A5,FO},
                          {REST,FO},//
                          {E5,FO},
                          {G5,FO},
                          {Cs5,FO},//
                          {D5,FO},
                          {A5,FO},
                          {REST,FO},//
                          {C5,FO},
                          {E5,FO},
                          {REST,FO},//
                          {C5,FO},
                          {E5,FO},
                          {REST,FO},//
                          {D5,FO},
                          {A5,FO},
                          {REST,FO},//
                          {D5,FO},
                          {A5,FO},
                          {REST,FO},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},////

                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {C3,EI},
                          {G3,EI},
                          {C4,EI},
                          {G3,EI},
                          {D4,EI},
                          {G3,EI},//

                          {D3,EI},//25
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {G2,EI},
                          {D3,EI},
                          {G3,EI},
                          {D3,EI},
                          {A3,EI},
                          {F3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {F3,EI},//
                          {E3,EI},
                          {Bb3,EI},
                          {Cs4,EI},
                          {A3,EI},
                          {C4,EI},
                          {G3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {D4,EI},
                          {G3,EI},//

                          {C3,EI},//31
                          {G3,EI},
                          {C4,EI},
                          {G3,EI},
                          {E4,EI},
                          {Bb3,EI},//
                          {A2,EI},
                          {E3,EI},
                          {A3,EI},
                          {E3,EI},
                          {C4,EI},
                          {G3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {D3,EI},
                          {A3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//
                          {C3,EI},
                          {F3,EI},
                          {D4,EI},
                          {A3,EI},
                          {E4,EI},
                          {A3,EI},//

                          {D2,SI},//36
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},//
                          {D2,SI},
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},////
                          {D2,SI},
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},//
                          {D2,SI},
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},////

                          {D2,SI},//38
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},//
                          {D2,SI},
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},////
                          {C2,SI},
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},//
                          {D2,SI},
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},////

                          {G2,SI},//40
                          {D3,SI},
                          {G3,SI},
                          {D3,SI},
                          {A3,SI},
                          {D3,SI},//
                          {D2,SI},
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},////
                          {D2,SI},
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},//
                          {D2,SI},
                          {A2,SI},
                          {D3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},////

                          {C2,SI},//42
                          {G2,SI},
                          {C3,SI},
                          {G2,SI},
                          {D3,SI},
                          {G2,SI},//
                          {E2,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},
                          {E3,SI},
                          {A2,SI},////
                          {D3,HA},
                          {Cs3,SI},
                          {C3,SI},
                          {B2,SI},
                          {Bb2,SI},////

                          {B2,24},////44

                          {Ab2,SI},//45
                          {Eb3,SI},
                          {Ab2,SI},
                          {Eb3,SI},//
                          {Bb3,SI},
                          {Eb3,SI},
                          {Ab2,SI},
                          {Eb3,SI},//
                          {Ab2,SI},
                          {Eb3,SI},
                          {Bb3,SI},
                          {Eb3,SI},////
                          {Ab2,SI},
                          {Eb3,SI},
                          {Ab3,SI},
                          {Eb3,SI},//
                          {Gb3,SI},
                          {Fb3,SI},
                          {Eb3,SI},
                          {Db3,SI},//
                          {Cb2,SI},
                          {Bb2,SI},
                          {Ab2,SI},
                          {Bb2,SI},////
                          {Ab2,SI},
                          {Eb3,SI},
                          {Ab2,SI},
                          {Eb3,SI},//
                          {Bb3,SI},
                          {Eb3,SI},
                          {Gb2,SI},
                          {Db3,SI},//
                          {Gb2,SI},
                          {Db3,SI},
                          {Gb3,SI},
                          {Db3,SI},////

                          {Ab2,SI},//48
                          {Eb3,SI},
                          {Ab2,SI},
                          {Eb3,SI},//
                          {Bb3,SI},
                          {Eb3,SI},
                          {Ab2,SI},
                          {Eb3,SI},//
                          {Ab2,SI},
                          {Eb3,SI},
                          {Ab3,SI},
                          {Gb3,SI},////
                          {Fb3,SI},
                          {Cb3,SI},
                          {Fb3,SI},
                          {Cb3,SI},//
                          {Ab3,SI},
                          {Fb3,SI},
                          {Eb3,SI},
                          {Ab3,SI},//
                          {Ab3,SI},
                          {Eb3,SI},
                          {Cb2,SI},
                          {Eb3,SI},////
                          {Db3,SI},
                          {Fb3,SI},
                          {Ab3,SI},
                          {Fb3,SI},//
                          {Db4,SI},
                          {Fb3,SI},
                          {Cb2,SI},
                          {Eb3,SI},//
                          {Gb3,SI},
                          {Eb3,SI},
                          {Cb3,SI},
                          {Eb3,SI},////

                          {Bb2,SI},
                          {Eb3,SI},
                          {Gb3,SI},
                          {Eb3,SI},
                          {Bb3,SI},
                          {Eb3,SI},
                          {Eb2,SI},
                          {Eb3,SI},
                          {Gb3,SI},
                          {Eb3,SI},
                          {Bb3,SI},
                          {Eb3,SI},////
                          {Ab2,SI},
                          {G2,SI},
                          {Gb2,SI},
                          {F2,SI},//
                          {Fb2,SI},
                          {Eb2,SI},
                          {D2,SI},
                          {Db2,SI},//
                          {C2,SI},
                          {Cb1,SI},
                          {B1,SI},
                          {Bb1,SI},////
                          {Ab1,24},////

                          {D5,FO},//54
                          {Fs5,FO},
                          {E5,FO},//
                          {Fs5,FO},
                          {D5,FO},
                          {Cs6,FO},//
                          {D6,FO},
                          {Fs5,FO},
                          {A5,FO},//
                          {D6,FO},
                          {Fs5,FO},
                          {REST,FO},//
                          {D6,FO},
                          {Fs5,FO},
                          {REST,FO},//
                          {D6,FO},
                          {Fs5,FO},
                          {REST,FO},//

                          {D6,FO},
                          {Fs5,FO},
                          {REST,FO},//
                          {D6,FO},
                          {Fs5,FO},
                          {REST,FO},//
                          {G5,FO},
                          {D6,FO},
                          {Cs6,FO},//
                          {D6,FO},
                          {A5,FO},
                          {B5,FO},//
                          {E5,FO},
                          {G5,FO},
                          {Cs6,FO},//
                          {Fs5,7},
                          {REST,1},
                          {Fs5,FO},
                          {REST,FO},//

                          {REST,FO},
                          {Cs5,FO},
                          {REST,FO},//
                          {REST,FO},
                          {Cs5,FO},
                          {REST,FO},//
                          {REST,2},
                          {Fs5,6},
                          {D5,FO},
                          {REST,FO},//
                          {REST,2},
                          {Fs5,30},
};



#endif /* SONGS_DAVYJONES_H_ */
